image: maven:3-eclipse-temurin-21-alpine

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - build
  - test
  - sonarqube-check
  - sonarqube-vulnerability-report
  - deploy

build:
  stage: build
  before_script:
    - apk add --no-cache openssh-client
    - chmod +x ci/setup-mvn-proxy.sh
    - ./ci/setup-mvn-proxy.sh
  script:
    - cd backend
    - mvn clean package -DskipTests
    - cp target/event-app-0.0.1-SNAPSHOT.jar app.jar
  artifacts:
    paths:
      - backend/app.jar

test-backend:
  stage: test
  before_script:
    - chmod +x ci/setup-mvn-proxy.sh
    - ./ci/setup-mvn-proxy.sh
  script:
    - cd backend
    - mvn test
  artifacts:
    reports:
      junit: backend/target/surefire-reports/TEST-*.xml


sonarqube-check:
  stage: sonarqube-check
  image: maven:3-eclipse-temurin-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - chmod +x ci/setup-mvn-proxy.sh
    - ./ci/setup-mvn-proxy.sh
  script:
    - cd backend
    - mvn verify sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.token=$SONAR_TOKEN
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop
    - SonarConfig

sonarqube-vulnerability-report:
  stage: sonarqube-vulnerability-report
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_URL}/api/issues/gitlab_sast_export?projectKey=g17_projettransversal2025-mif10_AZ0a45w9pItf3KCWeGy7&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop
    - SonarConfig
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json
  dependencies:
    - sonarqube-check


deploy:
  stage: deploy
  only:
    - BackAli
  before_script:
    - apk add --no-cache openssh-client rsync
    - eval "$(ssh-agent -s)"
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H "$VM_HOST" >> ~/.ssh/known_hosts
  script:
    - scp -o StrictHostKeyChecking=no backend/app.jar "$VM_USER@$VM_HOST:$VM_APP_DIR/app.jar"
    - rsync -av --delete -e "ssh -o StrictHostKeyChecking=no" frontend/public/ "$VM_USER@$VM_HOST:/var/www/monapp/"
    - ssh "$VM_USER@$VM_HOST" "sudo systemctl restart monapp && sudo systemctl reload nginx && sudo systemctl status monapp --no-pager"