name: EventApp CI
permissions:
  contents: read
  packages: write
on:
  push:
    branches:
    - main

  pull_request:
    branches:
      - main 

jobs:
  
  secret-scanning:
      name: Gitleaks scan 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
          with:
            fetch-depth: 0 #fetch all commits, not only the last

        - name: Scan for secrets
          run : |
            docker run --rm \
            -v "$PWD:/repo" \
            ghcr.io/gitleaks/gitleaks:latest \
            detect --verbose --source /repo
             
  build:
    needs: secret-scanning
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Setup Java
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compilation
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Tests unitaires 
        working-directory: backend
        run: mvn test


  SonarQube:
    needs: build
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Setup Java
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3
        with:
          distribution: temurin
          java-version: '21'
        
      - name: Scan & send to sonarqube server
        working-directory: backend
        run: |
          mvn verify sonar:sonar \
          -Dsonar.host.url=${{ secrets.SONAR_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.projectKey=event-app

  Semgrep:
    needs: build
    name: Semgrep SAST Analysis
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout du code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Backend main SAST Scan
        run: |
          docker run --rm \
            -v "${PWD}:/src" \
            semgrep/semgrep \
            semgrep scan \
            --config=p/java \
            --config=p/owasp-top-ten \
            /src/backend \
            --verbose \
            --error
            
      - name: Backend Particular cases
        run: |
          docker run --rm \
          -v "${PWD}:/src" \
          semgrep/semgrep \
          semgrep scan \
          --config=security/semgrep/jwt-security/hardcoded-jwt.yml \
          --config=security/semgrep/jwt-security/jwt-none-alg.yml \
          --config=security/semgrep/jwt-security/info-logger.yml \
          /src/backend \
          --verbose \
          --error
          
      
      - name: Frontend SAST Scan
        run: |
          docker run --rm \
            -v "${PWD}:/src" \
            semgrep/semgrep \
            semgrep scan \
            --config=p/javascript \
            --config=p/owasp-top-ten \
            /src/frontend \
            --verbose \
            --error

      - name: Pipeline SAST Scan
        run: |
          docker run --rm \
            -v "${PWD}:/src" \
            semgrep/semgrep \
            semgrep scan \
            --config=p/ci \
            /src/.github \
            --verbose \
            --error


  SCA:
    needs: build
    name: SCA scan 
    runs-on: ubuntu-latest

    steps:

      - name: Checkout du code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Setup Java
        uses:  actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven


      - name: Cache dependency-check database
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: .dependency-check-data # dossier à mettre en cache pour le prochain runner
          key: dependency-check-${{ runner.os }}-${{ github.run_id }} #identifiant du runner 
          restore-keys: |
            dependency-check-${{ runner.os }}-
            


      - name: OWASP dependency-check scan
        working-directory: backend
        run: |
          mvn org.owasp:dependency-check-maven:check \
          -DnvdApiKey=${{ secrets.NVD_API_KEY }} \
          -DdataDirectory=${{ github.workspace }}/.dependency-check-data \
          -DfailBuildOnCVSS=7 \
          -Dformats=HTML

      
      - name: Upload Dependency-Check report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: dependency-check-report
          path: backend/target/dependency-check-report.html


  Image-build-and-scan:
    needs: [ SonarQube, Semgrep, SCA]
    permissions:
      contents: read
      security-events: write
    name: Image build & Trivy scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout du code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Backend Image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ./backend
          file: ./backend/Dockerfile
          load: true # on ne push pas directement dans le registry, on la stocke pour l'analyse trivy
          tags: ghcr.io/${{ secrets.GH_ACTOR }}/eventapp-backend:${{ github.sha }}

      - name: Build Nginx image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: .
          file: ./nginx/Dockerfile
          load: true 
          tags: ghcr.io/${{ secrets.GH_ACTOR }}/eventapp-nginx:${{ github.sha }}


      - name: Scan Backend Image (report for Github Security)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: 'ghcr.io/${{ secrets.GH_ACTOR }}/eventapp-backend:${{ github.sha }}' # on utilise l'image du commit
          format: 'sarif'
          output: 'trivy-results-backend.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0' # on ne bloque pas la generation du rapport

      
      - name: Upload Trivy Backend results
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81
        if: always()
        with:
          sarif_file: 'trivy-results-backend.sarif'
          category: 'trivy-backend'


      - name: Scan Backend Image (security gate)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: 'ghcr.io/${{ secrets.GH_ACTOR }}/eventapp-backend:${{ github.sha }}' # on utilise l'image du commit
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'
        
       
      
      
      - name: Scan Nginx Image (report for Github Security)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: 'ghcr.io/${{ secrets.GH_ACTOR }}/eventapp-nginx:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results-nginx.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0'


      - name: Upload Trivy Nginx results
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81
        if: always()
        with:
          sarif_file: 'trivy-results-nginx.sarif'
          category: 'trivy-nginx'


      - name: Scan Nginx Image (security gate)
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: 'ghcr.io/${{ secrets.GH_ACTOR }}/eventapp-nginx:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'
        
        

      - name: Push Backend Image 
        run: docker push ghcr.io/${{ secrets.GH_ACTOR }}/eventapp-backend:${{ github.sha }} # on push l'image du commit (si tout est ok)

      - name: Push Nginx Image
        run: docker push ghcr.io/${{ secrets.GH_ACTOR }}/eventapp-nginx:${{ github.sha }}


      

      
      
          

    


        
          
        
        
    
          
          
            
          
