name: EventApp CI
on:
  push:
    branches:
    - main

  pull_request:
    branches:
      - main 

jobs:
  
  secret-scanning:
      name: Gitleaks scan 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 #fetch all commits, not only the last

        - name: Install Gitleaks
          run: |
            curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz -o gitleaks.tar.gz
            tar -xzf gitleaks.tar.gz
            sudo mv gitleaks /usr/local/bin/

        - name: Scan for Secrets
          run: |
            gitleaks detect --source . --verbose

             
  build:
    needs: secret-scanning
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compilation
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Tests unitaires 
        working-directory: backend
        run: mvn test

      - name: Analyse SonarQube
        working-directory: backend
        run: |
          mvn verify sonar:sonar \
          -Dsonar.host.url=${{ secrets.SONAR_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.projectKey=event-app
          
    
